# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Install Angular CLI globally
RUN npm install -g @angular/cli@16

# Build the Angular app
RUN ng build

# Expose port 4200 for the Angular app
EXPOSE 80

# Specify the command to run on container startup
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "80"]
