# Use the official Node.js 20 image as a base
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (or npm-shrinkwrap.json) to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Install Angular CLI globally in the container
RUN npm install -g @angular/cli@16

# Build the app
RUN ng build

# The port the app runs on
EXPOSE 80

# Serve the app using Angular CLI
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "80"]