FROM openjdk:17-oracle

WORKDIR /app

COPY . /app

RUN microdnf install findutils

RUN tr -d '\r' < gradlew > gradlew_temp && mv gradlew_temp gradlew && chmod +x gradlew

RUN ./gradlew build -x test

EXPOSE 8080

ENV NAME World

CMD ["java","-jar","build/libs/FundRipple.jar"]