FROM openjdk:17-oracle

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN microdnf install findutils
# Convert gradlew line endings to Unix format using tr
RUN tr -d '\r' < gradlew > gradlew_temp && mv gradlew_temp gradlew && chmod +x gradlew

# Run Gradle build when the container is built
RUN ./gradlew build -x test

# Make port 8080 available to the world outside this container
EXPOSE 8080

# Define environment variable
ENV NAME World

# Run java application
CMD ["java","-jar","build/libs/FundRipple.jar"]