# version: '3'
# services:
#   postgres:
#     image: postgres:latest
#     network_mode: "host"  # Use host network
#     environment:
#       POSTGRES_DB: fundripple
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

#   backend:
#     build:
#       context: FundRippleAPI
#     image: fundripple-app:latest
#     network_mode: "host"
#     depends_on:
#       - postgres
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/fundripple
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: postgres
#     ports:
#       - "8080:8080"

#   frontend:
#     build:
#       context: FundRippleGUI
#     ports:
#       - "80:80"

# volumes:
#   postgres-data:

version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: FundRipple
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./FundRippleAPI
    image: fundripple-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  frontend:
    build:
      context: FundRippleGUI
    ports:
      - "80:80"
volumes:
  postgres-data:

