version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: FundRipple
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./FundRippleAPI
    image: fundripple-backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - "C:/Users/Macie/shared:/app/resources"

  frontend:
    build:
      context: ./FundRippleGUI
    ports:
      - "80:80"
    volumes:
      - "C:/Users/Macie/shared:/app/src/assets"

volumes:
  postgres-data:
